### ISSUE TITLE
design benefit

### ISSUE THREAD

**Issue by jjhesk** [sniperHW/cooprative#1]
does this design can resolve lack of gorountine amounts in the cpu? put the task in sleep until there are enough goroutine to consume this task?

**Comment by sniperHW** [comment]
i want a system work like this. in a global view,it looks like a single thread program,
so it let me free from worried about race condition.

One way to achieve this aim is to used callback style.

a second way is cooprative,the advantages of single-threading are preserved while gaining the benefits of a synchronous interface. 

i was poor in english.i hope you konw what i mean.

**Comment by jjhesk** [comment]
sure. i got the idea to that can be used in handling large network request and it will still able to handle heavy load of work flows.. does it have any sample works that handles network requests?

**Comment by sniperHW** [comment]
you can look at example/test_http_get.go。there was mutil thread safe in fn。you can access any global data without lock protection。

**Comment by sniperHW** [comment]
close
